openapi: 3.0.0
info:
  title: ecomm API
  description: API for imaginary e-commerce platform
  termsOfService: http://example.com/terms-of-service
  version: '0.1'
paths:
  "/products":
    get:
      description: Get all products
      operationId: getProducts
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/product"
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
servers:
- url: http://localhost/api-spec
  description: Development server
